source 'https://github.com/CocoaPods/Specs.git'
source "git@gitlab.alibaba-inc.com:alipods/specs.git"
source "git@gitlab.alibaba-inc.com:alipods/specs-mirror.git"

platform :ios, '7.0'
#inhibit_all_warnings!

def common
    pod 'WeexSDK', :path=>'../../'
    pod 'WXDevtool'
    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2'
    pod 'ATSDK-Weex', '0.0.1'
    
    # WeexGcanvas is added by Weex Plugin, more info at https://market.dotwe.org/ext/list.htm
    pod 'WeexGcanvas'
    
    pod  'AliHATBAdapter',     '1.0.2.12-open-SNAPSHOT' # 接入层
    pod  'AliHAProtocol',     '1.0.4.5' # 协议层
    pod  'AliHACore',     '1.0.4.6'
    pod  'BizErrorReporter4iOS', '1.0.1.3' # 如果使用了TBCrashReporterAdapter，请移除相关依赖
    pod  'TBRest',     '1.0.0.18'
    pod  'UserTrack'
    
    pod  'TBCrashReporter',     '3.0.0.17'
    pod  'CrashReporter',     '1.3.6.17'
    pod  'JDYThreadTrace',     '1.0.0.12'
    
    pod  'AliHAPerformanceMonitor',     '1.0.4.6'
    pod  'BizErrorReporter4iOS',   '1.0.1.3'
end

target 'WeexDemo' do
    common
end

target 'WeexUITestDemo' do
    common
end
